<a href="https://colab.research.google.com/github/poolaNaveen/Banking-Industry-Analysis/blob/main/Array_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Sample data for 10 customers
customer_ids = np.array([f"CUST{i+1:03d}" for i in range(10)])
account_balances = np.array([120000, 85000, 43000, 98000, 150000, 67000, 25000, 105000, 39000, 76000])
credit_scores = np.array([820, 760, 690, 710, 880, 640, 600, 790, 720, 680])
transaction_counts = np.array([45, 60, 30, 55, 70, 25, 20, 65, 40, 50])
years_active = np.array([5, 8, 3, 6, 10, 2, 1, 7, 4, 5])
# Combine into a structured NumPy array
banking_data = np.column_stack((customer_ids, account_balances, credit_scores, transaction_counts, years_active))

# Display the dataset
print("Banking Dataset:\n", banking_data)


Banking Dataset:
 [['CUST001' '120000' '820' '45' '5']
 ['CUST002' '85000' '760' '60' '8']
 ['CUST003' '43000' '690' '30' '3']
 ['CUST004' '98000' '710' '55' '6']
 ['CUST005' '150000' '880' '70' '10']
 ['CUST006' '67000' '640' '25' '2']
 ['CUST007' '25000' '600' '20' '1']
 ['CUST008' '105000' '790' '65' '7']
 ['CUST009' '39000' '720' '40' '4']
 ['CUST010' '76000' '680' '50' '5']]


In [5]:
#Questions
# Q1.1: Create a 4x4 identity matrix
identity_matrix = np.eye(4)
print("Q1.1 - 4x4 Identity Matrix:\n", identity_matrix)

Q1.1 - 4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# Q1.2: Create an array of 8 zeros
zeros_array = np.zeros(8)
print("Q1.2 - Array of 8 Zeros:", zeros_array)

Q1.2 - Array of 8 Zeros: [0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#Q1.3: Create an array of 6 ones using np.ones()
ones_array = np.ones(6)
print("Array of 6 Ones:", ones_array)


Array of 6 Ones: [1. 1. 1. 1. 1. 1.]


In [13]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()##
Array = np.arange(0,16)
print("Array values of 0 to 15:", Array)

Array values of 0 to 15: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [2]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
import numpy as np
evenly_spaced_array = np.linspace(0, 100, 8)
print("Array with 8 evenly spaced values:", evenly_spaced_array)


Array with 8 evenly spaced values: [  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]
